# Analise arquivos raw movimentacao-bancaria.csv

In [1]:
import os
import pandas as pd
from pandasql import sqldf

pysqldf = lambda q: sqldf(q, globals())

In [2]:
BASE_DIR = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath('.'))))
DATA_DIR = os.path.join(BASE_DIR, 'data')
RAW_DIR =  os.path.join(DATA_DIR, 'raw')

In [4]:
df = pd.read_csv(os.path.join(RAW_DIR, 'movimentacoes_bancarias.csv'), sep=';')
df.shape

(1015, 8)

## Analise exploratória

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1015 entries, 0 to 1014
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id_movimento    1015 non-null   str
 1   data_movimento  1015 non-null   str
 2   tipo            994 non-null    str
 3   categoria       995 non-null    str
 4   descricao       995 non-null    str
 5   valor           995 non-null    str
 6   conta_bancaria  995 non-null    str
 7   conciliado      995 non-null    str
dtypes: str(8)
memory usage: 63.6 KB

In [6]:
df.isna().sum()

id_movimento       0
data_movimento     0
tipo              21
categoria         20
descricao         20
valor             20
conta_bancaria    20
conciliado        20
dtype: int64

In [7]:
df.head()

,id_movimento,data_movimento,tipo,categoria,descricao,valor,conta_bancaria,conciliado
0,MB000001,2026-05-14,Entrada,Outros,Outros - operação 1,11974.55,Banco B,Sim
1,MB000002,2026-03-15,Entrada,Energia,Energia - operação 2,329.88,Banco A,Sim
2,MB000003,2026-03-14,Saída,Pagamento fornecedor,NaN,1004.82,Banco B,Sim
3,MB000004,2026-04-21,Saída,Recebimento de cliente,Recebimento de cliente - operação 4,945.74,Banco A,Sim
4,MB000005,2026-08-13,Entrada,Outros,Outros - operação 5,11992.6,Banco C,Sim

In [8]:
df.tail()

,id_movimento,data_movimento,tipo,categoria,descricao,valor,conta_bancaria,conciliado
1010,MB000025,2026-06-04,Entrada,Outros,Outros - operação 25,1788.7,Banco A,Sim
1011,MB000243,2026-03-21,Entrada,Outros,Outros - operação 243,6344.79,Banco B,Sim
1012,MB000543,2026-06-12,Saída,Transferência,Transferência - operação 543,3313.07,Banco A,Sim
1013,MB000931,2026-07-29,Entrada,Energia,Energia - operação 931,7136.89,Banco A,sim
1014,MB000887,2026-03-18,Saída,Tarifa bancária,Tarifa bancária - operação 887,970.59,Banco C,Sim

In [9]:
df.sample(5)

,id_movimento,data_movimento,tipo,categoria,descricao,valor,conta_bancaria,conciliado
706,MB000707,2026-05-29,Saída,Outros,Outros - operação 707,16179.49,Banco A,Sim
660,MB000661,2026-04-18,Entrada,Salário,Salário - operação 661,14199.36,Banco B,Sim
40,MB000041,2026-03-08,Entrada,Impostos,Impostos - operação 41,10619.9,Banco C,sim
444,MB000445,2026-03-21,Saída,Transferência,Transferência - operação 445,16196.9,Banco B,Sim
993,MB000994,2026-03-14,Entrada,Salário,Salário - operação 994,7699.43,Banco A,Sim

In [10]:
df.isnull().sum()

id_movimento       0
data_movimento     0
tipo              21
categoria         20
descricao         20
valor             20
conta_bancaria    20
conciliado        20
dtype: int64

In [14]:
q = '''SELECT id_movimento
            , tipo
            , categoria
            , descricao
            , valor
            , conta_bancaria
            , conciliado
        FROM df
        WHERE tipo is null
            or categoria isnull
            or valor isnull
            or conta_bancaria isnull
            or conciliado isnull

'''
pysqldf(q)

,id_movimento,tipo,categoria,descricao,valor,conta_bancaria,conciliado
0,MB000027,Saída,Transferência,Transferência - operação 27,17689.4,NaN,Sim
1,MB000032,Entrada,Transferência,Transferência - operação 32,NaN,Banco B,Sim
2,MB000040,NaN,Salário,Salário - operação 40,10389.9,Banco C,Sim
3,MB000046,Entrada,NaN,Transferência - operação 46,13752.17,Banco C,Sim
4,MB000063,NaN,Aluguel,Aluguel - operação 63,8909.31,Banco C,Não
...,...,...,...,...,...,...,...
95,MB000939,Entrada,NaN,Salário - operação 939,16762.92,Banco C,Sim
96,MB000945,Entrada,Transferência,Transferência - operação 945,NaN,Banco B,Sim
97,MB000991,Saída,Energia,Energia - operação 991,7902.24,Banco B,NaN
98,MB000996,Entrada,Transferência,Transferência - operação 996,3656.59,Banco B,NaN
99,MB000488,NaN,Transferência,Transferência - operação 488,4023.92,Banco B,Sim